using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace TaskManagementApp
{
    // Base class for all tasks (abstract means it can't be directly created)
    public abstract class BaseTask
    {
        // Primary key, automatically generated by the database
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

        // Task title (required field for user input)
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string TaskType { get; set; } = string.Empty;

        // Constructor for the base task class needed 
        protected BaseTask() { }

        // Main Constructor for creating a task 
        protected BaseTask(int id, string title, string description, string taskType)
        {
            Id = id;
            Title = title;
            Description = description;
            TaskType = taskType;
        }

        // Constructor for creating a task with default values 
        public abstract void DisplayTaskType();
    }


}